version: '3.4'

services:
  logviewer:
    image: ng-ezLogger-viewer
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
